### ISSUE TITLE
The posts links in RSS feed are broken

### ISSUE THREAD

**Issue by lapwat** [ncase/blog#2]
The [RSS feed](https://blog.ncase.me/rss/) points to [https://blog.ncase.me/posts/X/]() rather than [https://blog.ncase.me/X/]().

**Comment by ncase** [comment]
![cat-screaming-cat](https://github.com/ncase/blog/assets/825858/24a6c9a1-bb7e-48f3-bf28-3868996be856)

Welp, that's what I get for not checking before deploying. Thanks for catching this, @lapwat !  It should be fixed now as of the latest commit: https://github.com/ncase/blog/blob/7aee6251305dc387aa61b08f9493b9a43b08ed2c/docs/feed.xml
